baseURL = 'https://giovannigiacometti.github.io'
languageCode = 'en-us'
title = 'Giovanni Giacometti'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """"""

# Collection to display on home
homeCollectionTitle = ''
homeCollection = false

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/giovannigiacometti/"

[[params.social]]
name = "github"
url = "https://github.com/GiovanniGiacometti"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "til"
url = "/til"

[[params.menu]]
name = "collection"
url = "/collection"

[[params.menu]]
name = "about"
url = "/about"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
