baseURL = 'https://giovannigiacometti.github.io'
languageCode = 'en-us'
title = 'Giovanni Giacometti'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """Welcome to my blog. I'm Giovanni, a Machine Learning Engineer. <br>
I just write about things I like. I hope you like them too!""" 

# Collection to display on home
homeCollectionTitle = 'Recent Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

showFooter = true
footerContent = "Proud to be different @ Giovanni Giacometti"

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/giovannigiacometti/"

[[params.social]]
name = "github"
url = "https://github.com/GiovanniGiacometti"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# [[params.menu]]
# name = "til"
# url = "/til"

# [[params.menu]]
# name = "collection"
# url = "/collection"

[[params.menu]]
name = "about"
url = "/about"


# Syntax highlight on code blocks
[markup]
defaultMarkdownHandler = "goldmark"
ignoreLogs = ['warning-goldmark-raw-html']
goldmark.renderer = { unsafe = true}
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"


[params.umami]
enable = true
websiteId = "629b75ef-d72c-4acf-9a5c-f1f6b554a06f"
jsLocation = "https://cloud.umami.is/script.js"

